version: '3.4'

services:
  db:
    image: rest-with-aspnet5-db
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context:
      dockerfile: db/Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: docker
  rest-with-aspnet5:
    image: ${DOCKER_REGISTRY-}restwithaspnet5
    build:
      context: .
      dockerfile: RestWithAspNet5/Dockerfile
